Query payment info
JackalLabs/canine-chain pull request #162
Opened 2022-12-07 19:06 UTC by nuggetnchill

Let me know if I missed anything

2022-12-07 19:20 UTC, TheMarstonConnell requested changes

2022-12-07 19:20 UTC, TheMarstonConnell commented on proto/canine_chain/storage/query.proto
> +        "/Jackal-dao/canine-chain/storage/payment_info";
I think it all should be lowercase

2022-12-07 19:21 UTC, nuggetnchill commented on proto/canine_chain/storage/query.proto
> +        "/Jackal-dao/canine-chain/storage/payment_info";
oops good catch

2022-12-08 03:54 UTC, TheMarstonConnell approved these changes

2022-12-08 03:56 UTC, merged