check if user already has some used space and apply it
JackalLabs/canine-chain pull request #167
Opened 2022-12-08 22:50 UTC by nuggetnchill

2022-12-08 22:55 UTC, dahn510 approved these changes
Thank you :+1:

2022-12-09 02:27 UTC, TheMarstonConnell requested changes

2022-12-09 02:27 UTC, TheMarstonConnell commented on x/storage/keeper/msg_server_buy_storage.go
> +			SpaceUsed:      payInfo.SpaceUsed,
@nuggetnchill can we make this so that if the spaceUsed is going to be greater than the bytes they requested to not allow it?

2022-12-09 14:44 UTC, TheMarstonConnell approved these changes

2022-12-09 14:44 UTC, merged